Realms:
  - name: "练气初期"
    value: 500
    success: 100
    failed: 0
  - name: "练气中期"
    value: 1000
    success: 95
    failed: 80
  - name: "练气后期"
    value: 2500
    success: 95
    failed: 80
  - name: "练气巅峰"
    value: 4000
    success: 95
    failed: 80
  - name: "筑基初期"
    value: 6000
    success: 90
    failed: 80
  - name: "筑基中期"
    value: 9000
    success: 90
    failed: 80
  - name: "筑基后期"
    value: 13000
    success: 90
    failed: 80
  - name: "筑基巅峰"
    value: 19000
    success: 90
    failed: 80
  - name: "金丹初期"
    value: 24000
    success: 85
    failed: 80
  - name: "金丹中期"
    value: 29000
    success: 85
    failed: 80
  - name: "金丹后期"
    value: 34000
    success: 85
    failed: 80
  - name: "金丹巅峰"
    value: 40000
    success: 85
    failed: 80
  - name: "元婴初期"
    value: 45000
    success: 80
    failed: 80
  - name: "元婴中期"
    value: 50000
    success: 80
    failed: 80
  - name: "元婴后期"
    value: 55000
    success: 80
    failed: 80
  - name: "元婴巅峰"
    value: 60000
    success: 80
    failed: 80
  - name: "化神初期"
    value: 65000
    success: 75
    failed: 100
  - name: "化神中期"
    value: 70000
    success: 75
    failed: 100
  - name: "化神后期"
    value: 75000
    success: 75
    failed: 100
  - name: "化神巅峰"
    value: 85000
    success: 75
    failed: 100
  - name: "炼虚初期"
    value: 90000
    success: 70
    failed: 100
  - name: "炼虚中期"
    value: 100000
    success: 70
    failed: 100
  - name: "炼虚后期"
    value: 105000
    success: 70
    failed: 100
  - name: "炼虚巅峰"
    value: 110000
    success: 70
    failed: 100
  - name: "合体初期"
    value: 115000
    success: 65
    failed: 100
  - name: "合体中期"
    value: 120000
    success: 65
    failed: 100
  - name: "合体后期"
    value: 125000
    success: 65
    failed: 100
  - name: "合体巅峰"
    value: 135000
    success: 65
    failed: 100
  - name: "大乘初期"
    value: 140000
    success: 60
    failed: 100
  - name: "大乘中期"
    value: 145000
    success: 60
    failed: 100
  - name: "大乘后期"
    value: 150000
    success: 60
    failed: 100
  - name: "大乘巅峰"
    value: 160000
    success: 60
    failed: 100
  - name: "渡劫期1重"
    value: 165000
    success: 30
    failed: 300
  - name: "渡劫期2重"
    value: 170000
    success: 30
    failed: 300
  - name: "渡劫期3重"
    value: 175000
    success: 30
    failed: 300
  - name: "渡劫期4重"
    value: 180000
    success: 30
    failed: 300
  - name: "渡劫期5重"
    value: 185000
    success: 30
    failed: 300
  - name: "渡劫期6重"
    value: 190000
    success: 30
    failed: 300
  - name: "渡劫期7重"
    value: 195000
    success: 30
    failed: 300
  - name: "渡劫期8重"
    value: 200000
    success: 30
    failed: 300
  - name: "渡劫期9重"
    value: 205000
    success: 30
    failed: 300
  - name: "渡劫期10重"
    value: 210000
    success: 30
    failed: 300
  - name: "渡劫期11重"
    value: 215000
    success: 30
    failed: 300
  - name: "渡劫期12重"
    value: 220000
    success: 30
    failed: 300
  - name: "散仙一重"
    value: 225000
    success: 20
    failed: 300
  - name: "散仙二重"
    value: 230000
    success: 20
    failed: 300
  - name: "散仙三重"
    value: 235000
    success: 20
    failed: 300
  - name: "散仙四重"
    value: 240000
    success: 20
    failed: 300
  - name: "散仙五重"
    value: 245000
    success: 20
    failed: 300
  - name: "散仙六重"
    value: 250000
    success: 20
    failed: 300
  - name: "散仙七重"
    value: 255000
    success: 20
    failed: 300
  - name: "散仙八重"
    value: 260000
    success: 20
    failed: 300
  - name: "散仙九重"
    value: 265000
    success: 20
    failed: 300
  - name: "地仙一重"
    value: 315000
    success: 20
    failed: 300
  - name: "地仙二重"
    value: 330000
    success: 20
    failed: 300
  - name: "地仙三重"
    value: 345000
    success: 20
    failed: 300
  - name: "地仙四重"
    value: 360000
    success: 20
    failed: 300
  - name: "地仙五重"
    value: 375000
    success: 20
    failed: 300
  - name: "地仙六重"
    value: 390000
    success: 20
    failed: 300
  - name: "地仙七重"
    value: 405000
    success: 20
    failed: 300
  - name: "地仙八重"
    value: 420000
    success: 20
    failed: 300
  - name: "地仙九重"
    value: 435000
    success: 20
    failed: 300
  - name: "天仙一重"
    value: 450000
    success: 20
    failed: 300
  - name: "天仙二重"
    value: 470000
    success: 20
    failed: 300
  - name: "天仙三重"
    value: 490000
    success: 20
    failed: 300
  - name: "天仙四重"
    value: 510000
    success: 20
    failed: 300
  - name: "天仙五重"
    value: 530000
    success: 20
    failed: 300
  - name: "天仙六重"
    value: 550000
    success: 20
    failed: 300
  - name: "天仙七重"
    value: 570000
    success: 20
    failed: 300
  - name: "天仙八重"
    value: 590000
    success: 20
    failed: 300
  - name: "天仙九重"
    value: 610000
    success: 20
    failed: 300
  - name: "金仙一重"
    value: 630000
    success: 20
    failed: 300
  - name: "金仙二重"
    value: 655000
    success: 20
    failed: 300
  - name: "金仙三重"
    value: 680000
    success: 20
    failed: 300
  - name: "金仙四重"
    value: 705000
    success: 20
    failed: 300
  - name: "金仙五重"
    value: 730000
    success: 20
    failed: 300
  - name: "金仙六重"
    value: 755000
    success: 20
    failed: 300
  - name: "金仙七重"
    value: 780000
    success: 20
    failed: 300
  - name: "金仙八重"
    value: 805000
    success: 20
    failed: 300
  - name: "金仙九重"
    value: 830000
    success: 20
    failed: 300
  - name: "玄仙一重"
    value: 855000
    success: 20
    failed: 300
  - name: "玄仙二重"
    value: 885000
    success: 20
    failed: 300
  - name: "玄仙三重"
    value: 915000
    success: 20
    failed: 300
  - name: "玄仙四重"
    value: 945000
    success: 20
    failed: 300
  - name: "玄仙五重"
    value: 975000
    success: 20
    failed: 300
  - name: "玄仙六重"
    value: 1005000
    success: 20
    failed: 300
  - name: "玄仙七重"
    value: 1035000
    success: 20
    failed: 300
  - name: "玄仙八重"
    value: 1065000
    success: 20
    failed: 300
  - name: "玄仙九重"
    value: 1095000
    success: 20
    failed: 300
  - name: "灵仙一重"
    value: 1125000
    success: 20
    failed: 300
  - name: "灵仙二重"
    value: 1160000
    success: 20
    failed: 300
  - name: "灵仙三重"
    value: 1195000
    success: 20
    failed: 300
  - name: "灵仙四重"
    value: 1230000
    success: 20
    failed: 300
  - name: "灵仙五重"
    value: 1265000
    success: 20
    failed: 300
  - name: "灵仙六重"
    value: 1300000
    success: 20
    failed: 300
  - name: "灵仙七重"
    value: 1335000
    success: 20
    failed: 300
  - name: "灵仙八重"
    value: 1370000
    success: 20
    failed: 300
  - name: "灵仙九重"
    value: 1405000
    success: 20
    failed: 300
  - name: "真仙一重"
    value: 1440000
    success: 20
    failed: 300
  - name: "真仙二重"
    value: 1480000
    success: 20
    failed: 300
  - name: "真仙三重"
    value: 1520000
    success: 20
    failed: 300
  - name: "真仙四重"
    value: 1560000
    success: 20
    failed: 300
  - name: "真仙五重"
    value: 1600000
    success: 20
    failed: 300
  - name: "真仙六重"
    value: 1640000
    success: 20
    failed: 300
  - name: "真仙七重"
    value: 1680000
    success: 20
    failed: 300
  - name: "真仙八重"
    value: 1720000
    success: 20
    failed: 300
  - name: "真仙九重"
    value: 1760000
    success: 20
    failed: 300
  - name: "仙君一重"
    value: 1800000
    success: 20
    failed: 300
  - name: "仙君二重"
    value: 1845000
    success: 20
    failed: 300
  - name: "仙君三重"
    value: 1890000
    success: 20
    failed: 300
  - name: "仙君四重"
    value: 1935000
    success: 20
    failed: 300
  - name: "仙君五重"
    value: 1980000
    success: 20
    failed: 300
  - name: "仙君六重"
    value: 2025000
    success: 20
    failed: 300
  - name: "仙君七重"
    value: 2070000
    success: 20
    failed: 300
  - name: "仙君八重"
    value: 2115000
    success: 20
    failed: 300
  - name: "仙君九重"
    value: 2160000
    success: 20
    failed: 300
  - name: "仙王一重"
    value: 2205000
    success: 20
    failed: 300
  - name: "仙王二重"
    value: 2255000
    success: 20
    failed: 300
  - name: "仙王三重"
    value: 2305000
    success: 20
    failed: 300
  - name: "仙王四重"
    value: 2355000
    success: 20
    failed: 300
  - name: "仙王五重"
    value: 2405000
    success: 20
    failed: 300
  - name: "仙王六重"
    value: 2455000
    success: 20
    failed: 300
  - name: "仙王七重"
    value: 2505000
    success: 20
    failed: 300
  - name: "仙王八重"
    value: 2555000
    success: 20
    failed: 300
  - name: "仙王九重"
    value: 2605000
    success: 20
    failed: 300
  - name: "仙帝一重"
    value: 2655000
    success: 20
    failed: 300
  - name: "仙帝二重"
    value: 2710000
    success: 20
    failed: 300
  - name: "仙帝三重"
    value: 2765000
    success: 20
    failed: 300
  - name: "仙帝四重"
    value: 2820000
    success: 20
    failed: 300
  - name: "仙帝五重"
    value: 2875000
    success: 20
    failed: 300
  - name: "仙帝六重"
    value: 2930000
    success: 20
    failed: 300
  - name: "仙帝七重"
    value: 2985000
    success: 20
    failed: 300
  - name: "仙帝八重"
    value: 3040000
    success: 20
    failed: 300
  - name: "仙帝九重"
    value: 3095000
    success: 20
    failed: 300
  - name: "仙尊一重"
    value: 3150000
    success: 10
    failed: 300
  - name: "仙尊二重"
    value: 3210000
    success: 10
    failed: 300
  - name: "仙尊三重"
    value: 3270000
    success: 10
    failed: 300
  - name: "仙尊四重"
    value: 3330000
    success: 10
    failed: 300
  - name: "仙尊五重"
    value: 3390000
    success: 10
    failed: 300
  - name: "仙尊六重"
    value: 3450000
    success: 10
    failed: 300
  - name: "仙尊七重"
    value: 3510000
    success: 10
    failed: 300
  - name: "仙尊八重"
    value: 3570000
    success: 10
    failed: 300
  - name: "仙尊九重"
    value: 3630000
    success: 10
    failed: 300
  - name: "道祖"
    value: 3690000
    success: 10
    failed: 1000
  - name: "道境圣人"
    value: 5000000
    success: 10
    failed: 2000
  - name: "无上仙帝"
    value: 10000000
    success: 10
    failed: 5000
  - name: "永恒•仙境"
    value: 20000000
    success: 5
    failed: 50000