#修仙全局开关
xiuxian: true

#主人不受冷却限制
mastercd: false

#是否强制用#触发
forceSharp: false

#是否启用黑白群名单 0 - 无   1 - 黑名单   2 - 白名单
group: 0

#黑名单群
blackGroup: []

#白名单群
whiteGroup: []

#输出文本样式 0 - 普通文本   1 - Markdown
TextStyle: 0

#修仙权限
master: []