#修仙排行榜称号
rankTitle:
  validDays: 7  #修仙排行榜称号有效期（0表示永久，单位：天）
  cron: 0 0 0 ? * 1  #修仙排行榜定时发放称号cron表达式
  cult:
    - 万劫不朽
    - 混元无极
    - 太初归真
  ls:
    - 聚宝成山
    - 富甲八荒
    - 钱通神域
  power:
    - 一念星陨
    - 战意焚海
    - 杀伐独尊
  retreat:
    - 坐忘千秋
    - 时间囚徒
    - 道茧未破

#修仙清理过期称号
cleanTitle:
  cron: 0 0 0 * * *  #修仙定时清理过期称号cron表达式