#修炼冷却（秒）
xiulian: 300

#开采冷却（秒）
kaicai: 300

#修炼修为上限
maxcult: 3000

#修炼修为下限
mincult: 1000

#开采灵石上限
maxls: 3000

#开采灵石下限
minls: 1000

#闭关设置
retreat: 
  cult: 5000  #修为
  max: 24  #闭关上限（单位：时，为0则无上限）

#签到奖励
sign:
  cult: 38888
  ls: 18888

#切磋配置
pvp:
  atk_cd: 60   #发起方切磋冷却（单位：秒）
  def_cd: 120  #接受方切磋冷却（单位：秒）

#战力计算公式（修为：cult，境界：realm）
powerFormula: "realm / 10 * cult / 100"